name: CI/CD

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
  
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-
      - name: Run static analysis
        run: mvn checkstyle:checkstyle

  test:
    runs-on: ubuntu-latest
    needs: static-analysis
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-
      - name: Run Tests
        run: mvn -B -e test

  build-and-package-pr:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/test'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ github.base_ref }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-
      - name: Build with Maven
        run: mvn -B -e package -DskipTests
      - name: Build Docker Image
        run: docker build -t petclinic:${{ github.sha }} .
      - name: Save Docker image to tar
        run: |
          mkdir -p /tmp/docker-image
          docker save petclinic:${{ github.sha }} -o /tmp/docker-image/petclinic-image.tar
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: petclinic-image
          path: /tmp/docker-image/petclinic-image.tar

  build-and-package-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ github.base_ref }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: petclinic-image
          path: /tmp/docker-image
      - name: Load Docker image from artifact
        run: docker load -i /tmp/docker-image/petclinic-image.tar
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: false
          RELEASE_BRANCHES: main
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Retag and push image
        run: |
          docker tag petclinic:${{ github.sha }} ghcr.io/${{ github.repository }}/petclinic:v${{ steps.versioning.outputs.new_tag }}
          docker push ghcr.io/${{ github.repository }}/petclinic:v${{ steps.versioning.outputs.new_tag }}

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    needs: build-and-package-main
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install SSH Key and Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Retrieve Infrastructure Outputs from Parameter Store
        id: get_infra_outputs
        run: |
          EC2_IP=$(aws ssm get-parameter --name "/myapp/ec2_public_ip" --query "Parameter.Value" --output text)
          DB_ENDPOINT=$(aws ssm get-parameter --name "/myapp/db_endpoint" --query "Parameter.Value" --output text)
          echo "ec2_ip=$EC2_IP" >> $GITHUB_OUTPUT
          echo "db_endpoint=$DB_ENDPOINT" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Deploy to Server
        env:
          GHCR_PAT: ${{ secrets.GHCR_PULL_TOKEN }}
          MYSQL_HOST: ${{ steps.get_infra_outputs.outputs.db_endpoint }}
        run: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.SSH_USER }}@${{ steps.get_infra_outputs.outputs.ec2_ip }} << EOF
            # Log in to ghcr.io
            echo "$GHCR_PAT" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            # Get the new image ID
            NEW_IMAGE_ID=$(docker inspect --format='{{.Id}}' ghcr.io/${{ github.repository }}/petclinic:v$(git describe --tags $(git rev-list --tags --max-count=1)))

            # Check if the container exists and stop/remove it
            if docker ps -a --format '{{.Names}}' | grep -q 'petclinic'; then
              docker stop petclinic
              docker rm petclinic
            fi
            # Pull the latest image
            docker pull ghcr.io/${{ github.repository }}/petclinic:v$(git describe --tags $(git rev-list --tags --max-count=1))

            # Run the new container
            docker run -d --name petclinic -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://$MYSQL_HOST:3306/${{secrets.MYSQL_DATABASE}}?useSSL=false \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_USER }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              -e SPRING_PROFILES_ACTIVE=mysql \
              ghcr.io/${{ github.repository }}/petclinic:v$(git describe --tags $(git rev-list --tags --max-count=1))

            # Prune old images, excluding the newly deployed image
            docker image prune -a -f --filter "until=24h" --filter "label!=newly_deployed=$NEW_IMAGE_ID"

            # Print application URL
            echo "Application deployed at http://${{ steps.get_infra_outputs.outputs.ec2_ip }}:8080"
          EOF
          