name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-
      - name: Run static analysis
        run: mvn checkstyle:checkstyle

  test:
    runs-on: ubuntu-latest
    needs: static-analysis
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-
      - name: Run Tests
        run: mvn -B -e test

  build-and-cache-artifact-pr:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ github.base_ref }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-
      - name: Build with Maven
        run: mvn -B -e package -DskipTests
      - name: Store build artifact
        uses: actions/upload-artifact@v4
        with:
          name: petclinic-app
          path: target/*.jar

  build-and-cache-artifact-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ github.base_ref }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-
      - name: Build with Maven
        run: mvn -B -e package -DskipTests
      - name: Store build artifact
        uses: actions/upload-artifact@v4
        with:
          name: petclinic-app
          path: target/*.jar
      
  create-artifact-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build-and-cache-artifact-pr
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: petclinic-app
          path: target
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Construct Docker tag
        id: set_docker_tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)
          TAG="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:pr-${{ github.event.number }}-${SHORT_SHA}"
          echo "docker_tag=$TAG" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.set_docker_tag.outputs.docker_tag }}

  create-artifact-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-cache-artifact-main
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: petclinic-app
          path: target

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: false 
          RELEASE_BRANCHES: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construct Docker tag
        id: set_docker_tag
        run: |
          TAG="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.versioning.outputs.new_tag }}"
          echo "docker_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.set_docker_tag.outputs.docker_tag }}

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: create-artifact-main
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SSH Key and Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Retrieve Infrastructure Outputs from Parameter Store
        id: get_infra_outputs
        run: |
          EC2_IP=$(aws ssm get-parameter --name "/myapp/ec2_public_ip" --query "Parameter.Value" --output text)
          DB_ENDPOINT=$(aws ssm get-parameter --name "/myapp/db_endpoint" --query "Parameter.Value" --output text)
          DNS_NAME=$(aws ssm get-parameter --name "/myapp/lb_dns_name" --query "Parameter.Value" --output text)
          echo "ec2_ip=$EC2_IP" >> $GITHUB_OUTPUT
          echo "db_endpoint=$DB_ENDPOINT" >> $GITHUB_OUTPUT
          echo "dns_name=$DNS_NAME" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Construct Docker tag
        id: set_docker_tag
        run: |
          TAG="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo "docker_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Deploy to Server
        env:
          GHCR_PAT: ${{ secrets.GHCR_PULL_TOKEN }}
          MYSQL_HOST: ${{ steps.get_infra_outputs.outputs.db_endpoint }}
        run: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.SSH_USER }}@${{ steps.get_infra_outputs.outputs.ec2_ip }} << EOF
            # Log in to ghcr.io
            echo "$GHCR_PAT" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            # Get the new image ID
            NEW_IMAGE_ID=$(docker inspect --format='{{.Id}}' ${{ steps.set_docker_tag.outputs.docker_tag }})

            # Check if the container exists and stop/remove it
            if docker ps -a --format '{{.Names}}' | grep -q 'petclinic'; then
              docker stop petclinic
              docker rm petclinic
            fi
            # Pull the latest image
            docker pull ${{ steps.set_docker_tag.outputs.docker_tag }}

            # Run the new container
            docker run -d --name petclinic -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://$MYSQL_HOST:3306/${{secrets.MYSQL_DATABASE}}?useSSL=false \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_USER }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              -e SPRING_PROFILES_ACTIVE=mysql \
              ${{ steps.set_docker_tag.outputs.docker_tag }}

            # Prune old images, excluding the newly deployed image
            docker image prune -a -f --filter "until=24h" --filter "label!=newly_deployed=$NEW_IMAGE_ID"

            # Print application URL
            echo "Application deployed at http://${{ steps.get_infra_outputs.outputs.dns_name }}"
          EOF
          